language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
install: pip install --use-mirrors .
script: python setup.py test
notifications:
    irc:
        channels: 
            - "irc.mozilla.org#services-dev"
        on_success: change
